version: "3.9"
name: subscription-local

networks:
  subscription_network:
    driver: bridge

services:
  postgres:
    restart: always
    image: postgres:15.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=subscription
    volumes:
      - postgres:/data/postgres
    ports:
      - "15436:5432"
    networks:
      - subscription_network

volumes:
  postgres: