version: "3.9"

services:
  backend:
    image: ghcr.io/valykhin/subscriptions:0.0.1-SNAPSHOT
    restart: always
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
#      SPRING_APPLICATION_JSON: '{"logging":{"level":{"ru":{"ivalykhin":{"subscriptions":"INFO"}}}}}'
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:-50}
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:-5000}
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: ${MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED:-true}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:-health,info,prometheus,metrics}
      JAVA_OPTS: "-Xms1024m -Xmx1536m -XX:+UseG1GC"
      JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 2Gb
        reservations:
          cpus: '2.0'
          memory: 2Gb
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:15.0
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=subscriptions
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres: