spring:
  application:
    name: subscriptions
  jpa:
    show-sql: false
    properties:
      hibernate:
        hbm2ddl.auto: none
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    auto-commit: false
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:50}
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:5000}
      validation-timeout: 3000
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    enabled: true

retry:
  optimistic-lock:
    max-attempts: ${RETRY_OPTIMISTIC_LOCK_MAX_ATTEMPTS:5}
    delay: ${RETRY_OPTIMISTIC_LOCK_DELAY:50}
    multiplier: ${RETRY_OPTIMISTIC_LOCK_MULTIPLIER:1.5}

info:
  application:
    name: ${spring.application.name}
    description: Subscriptions application
    version: '@project.version@'
    spring-boot-version: '@project.parent.version@'